### ISSUE TITLE
Does Brickpi.UWP work with BrickPi3 and RaspberryPi 3 ?

### ISSUE THREAD

**Issue by CaptnMo** [perpetualKid/BrickPi.Uwp#2]
Hello,
just a short question, will Brickpi.UWP work with new BrickPi3? I try to get it running but no success so far. 
I am using Brickpi3 with actual Firmware 1.4.4 on Windows 10 IoT 10.0.15063.0. I have run the regex command as mentionned in the documentation for the serial port.

This is the code:
            Brick brick = await Brick.InitializeInstance("Uart0");
            var o = await Brick.FindSerialDevice();

            int version = await brick.GetBrickVersion();
            Debug.WriteLine(string.Format("Brick Version: {0}", version));

            brick.Arduino1Led.Light = false; 
            brick.Arduino2Led.Light = false;	

            Motor motorD = brick.Motors[MotorPort.Port_MD];
            
            motorD.Velocity = -50;
            motorD.Enabled = true;
            //...	
            motorD.Enabled = false; //set the motor to float
                                    //...
            motorD.Velocity = 0;

Version will return 0. I get no error but nothing happens. Using the Dexter Rasbian Version the motor is running so I assume that the hardware is ok.

Thanks in Advance

**Comment by perpetualKid** [comment]
as far I can see the BrickPi3 uses SPI for communication, compared to the (older) BrickPi+ using  serial communication. BrickPi.UWP has been developed and tested for BrickPi+. 
Given this breaking change in underlying BrickPi communication layer, an implementation for BrickPi3 seem to require an complete rewrite.
